import React, { useState, useEffect } from 'react';
import { Quote, Loader2 } from 'lucide-react';

export default function QuoteOfTheDay() {
    const [quote, setQuote] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchQuote = async () => {
            try {
                // Fetch random quote from Islamic Network API
                const response = await fetch('https://quotes.api.islamic.network/v1/quotes/random');
                if (response.ok) {
                    const data = await response.json();
                    setQuote(data.data);
                }
            } catch (error) {
                console.error("Failed to fetch quote", error);
            } finally {
                setLoading(false);
            }
        };

        fetchQuote();
    }, []);

    if (loading) {
        return (
            <div className="w-full bg-[#0a0a0a] border border-[#333] p-8 rounded-3xl text-center shadow-2xl flex flex-col items-center justify-center min-h-[200px]">
                <Loader2 className="w-8 h-8 animate-spin text-amber-500 mb-4" />
                <span className="text-xs text-gray-500 uppercase tracking-widest">Recherche d'une sagesse...</span>
            </div>
        );
    }

    if (!quote) return null;

    // The API provides French translations generated by Claude!
    const frenchText = quote.translations?.fr?.text || "Traduction non disponible.";
    const originalText = quote.original?.text || "";

    return (
        <div className="w-full bg-[#0a0a0a] border border-[#333] p-8 rounded-3xl text-center relative overflow-hidden shadow-2xl group hover:border-amber-500/50 transition-colors">
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-amber-500 via-amber-400 to-transparent opacity-50"></div>
            
            <div className="flex items-center justify-center mb-6">
                <Quote className="text-amber-500/40 w-10 h-10 transform -scale-x-100" />
            </div>

            <p className="text-xl sm:text-2xl font-serif text-white mb-6 leading-relaxed italic">
                "{frenchText}"
            </p>

            {originalText && (
                <p className="text-gray-500 text-sm max-w-lg mx-auto mb-6 leading-relaxed" dir="auto">
                    "{originalText}"
                </p>
            )}

            <div className="inline-flex flex-col items-center">
                <span className="text-xs text-amber-500 font-bold uppercase tracking-wider mb-1">
                    Citation du Jour
                </span>
                <span className="text-[10px] text-gray-600 font-mono">Via Islamic Network API</span>
            </div>
        </div>
    );
}
